### ISSUE TITLE
database credentials

### ISSUE THREAD

**Issue by DakotaDong** [atulmy/fullstack-graphql#12]
Hey! What should I do for this step: Modify /api/src/config/database.json for database credentials? Thanks!

**Comment by atulmy** [comment]
You need to either install MySQL locally or use online free hosting (remotemysql.com) for testing and get the credentials.

Example credentials:
Username: root
Password: 74TMPD8B

Then edit the file accordingly:
```
{
  "development": {
    "username": "root",
    "password": "74TMPD8B",
    "database": "graphql",
    "host": "127.0.0.1",
    "dialect": "mysql"
  },
  "production": {
    ...
  }
}
```
