### ISSUE TITLE
Looking for contributors! 👨‍💻👩‍💻

### ISSUE THREAD

**Issue by atulmy** [atulmy/fullstack-graphql#2]
Created as an experiment for the next project I was going to work on, decided to share the experiment which surprisingly seems to getting attention by GraphQL and React enthusiasts.

If you are **interested in contributing** to the codebase in any possible way to make it better (build processes, webpack, babel, HMR, better code structure, feature additions, docker image, deployment scripts, optimizations, bug fixes, etc.) please feel free to send PR, open issues or give suggestions.

In **open source**, we trust!

**Comment by yadunandan004** [comment]
Hey atul,
I'll try to do my best. Kindly add me as a contributor.

Thank You
Yadu Nandan

**Comment by vikas0121** [comment]
Hi,
I'm working on some node.js projects and integration of third party api's. Allow me as a contributor.
Thanks
