### ISSUE TITLE
add SSR

### ISSUE THREAD

**Issue by theskillwithin** [atulmy/fullstack-graphql#3]
Server Side Rendering the react app

https://reactjs.org/docs/react-dom-server.html#rendertostring

**Comment by atulmy** [comment]
@theskillwithin you can find SSR implementation here: https://github.com/atulmy/universal-react (updated with React 16 and the new `hydrate` function.

I'm not very skilled with Babel / Webpack and `create-react-app` provides complete run and build scripts. If you can contribute to the `universal-react` package with proper babel/webpack along with HMR configurations, I can replicate it in this (`fullstack-graphql`) repository and implement SSR.
