### ISSUE TITLE
Basic register/login mechanism ?

### ISSUE THREAD

**Issue by erdalstk** [atulmy/fullstack-graphql#8]
Hi, first of all awesome starter. Thanks for this starter @atulmy 
You must be given lots of effort to put these technologies working together.

So come to the point, do you think to add basic register/login mechanism to this starter ?

Kind regards.

**Comment by atulmy** [comment]
Hi @erdalstk,

Glad you found the project interesting.

For authentication and other advanced features, you can check https://github.com/atulmy/crate. Look at the features section on the readme to see full list.

There is another open source application I'm currently working on: https://github.com/atulmy/hire-smart and you can see the live version of same codebase here: https://hiresmart.app/. This comes with  all the features from `fullstack-graphql` and `crate` along with deployment using Docker.

Hit me up if you have any questions. Feel free to contribute to any of these projects.

Happy coding!
